# Usa la imagen base de Jupyter Pyspark Notebook
FROM quay.io/jupyter/pyspark-notebook

# Copia los archivos necesarios al directorio de trabajo del contenedor
COPY . /home/jovyan/work

# Establece el directorio de trabajo
WORKDIR /home/jovyan/work

